version: "3.7"
services:
  backend:
    build:
      context: ./back/
      dockerfile: Dockerfile
    image: back
    ports:
      - 7777:80
    networks:
      - full
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    image: front
    networks:
      - full
    ports:
      - 9999:80
    depends_on:
      - backend
networks:
  full: